# Setup
title:               Wikilabs
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme .'
url:                 https://dopolavoro-matematico.github.io/
baseurl:             ''
paginate:            5
permalink: 			 /:year/:month/:day/:title:output_ext
repository: 		 etcware/Dopolavoro-Matematico

# About/contact
author:
  name:              alendo
  url:               https://twitter.com/alendo
  email:             alendo@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-category-pages

# Custom vars
version:             0.1.0
google_analytics_id: #UA-XXXX-Y
